server:
  port: 8080
  error:
    include-message: always

spring:
  main:
    web-application-type: servlet
  datasource:
    url: jdbc:postgresql://localhost:5332/customer
    username: amigoscode
    password: password
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true